"""Pydantic response models for FastAPI."""
from models.election import (
    Election,
    ElectionDetail,
    Party,
    Candidate,
    CandidateDetail,
    CandidateSearchResult,
    ElectionResult,
    NationalTotal,
    PartySeat,
    PartyByDate,
    PartyListVote,
    ElectedCount,
    ElectionCycle,
    ElectionMilestone,
    RecallResult,
    Platform,
    PlatformSource,
    PlatformImage,
    CandidatePlatformStatus,
    PresidentialTrend,
    PartyListTrend,
    MayoralHistory,
    District,
    TotalVotes,
    TownshipResult,
)

__all__ = [
    "Election", "ElectionDetail", "Party", "Candidate", "CandidateDetail",
    "CandidateSearchResult", "ElectionResult", "NationalTotal", "PartySeat",
    "PartyByDate", "PartyListVote", "ElectedCount", "ElectionCycle",
    "ElectionMilestone", "RecallResult",
    "Platform", "PlatformSource", "PlatformImage", "CandidatePlatformStatus",
    "PresidentialTrend", "PartyListTrend", "MayoralHistory", "District",
    "TotalVotes", "TownshipResult",
]
